title: Learn Without Limits CIC Blog
description: Blog articles from Learn Without Limits CIC on ALN, education, online safety and system reform.
baseurl: ""
url: "https://blog.learnwithoutlimitscic.org"

markdown: kramdown
permalink: /:year/:month/:day/:title/

timezone: Europe/London

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "en"

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - README.md
